# Site settings
title: Election Business Process Modeling
description: "Election Business Process Modeling"
baseurl: "/ElectionModeling" # the subpath of your site,  e.g. /blog
url: "https://pages.nist.gov/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude:
- ".ruby-version"
- ".jekyll-metadata"
- ".gitignore"
- ".travis.yml"
- todo.txt
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- CONTRIBUTING.md
- LICENSE.md

# GitHub information
org_name: usnistgov
repo_name: ElectionModeling

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: /ElectionModeling/

host: 0.0.0.0
